#!/usr/bin/env node
// Self-contained installation/diagnosis. No credential reads or package downloads.
import { existsSync, mkdirSync, readFileSync, realpathSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { buildConfig, loadConfigFile } from '../runtime/config.mjs';
import { assertSupportedHost, discoverPaths, isFile, SUPPORTED_NODE } from '../runtime/discovery.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const VALUE_FLAGS = new Set(['--zcode-bin', '--provider-file', '--codex-home', '--skills-dir']);
const BOOL_FLAGS = new Set(['--check', '--replace', '--help']);

export function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const flag = argv[i];
    if (Object.hasOwn(args, flag)) throw new Error(`重复参数：${flag}`);
    if (BOOL_FLAGS.has(flag)) args[flag] = true;
    else if (VALUE_FLAGS.has(flag)) {
      const value = argv[++i];
      if (!value || value.startsWith('--') || /[\r\n\0]/.test(value)) throw new Error(`参数缺少有效路径：${flag}`);
      args[flag] = value;
    } else throw new Error(`未知参数：${flag}`);
  }
  if (args['--codex-home'] && args['--skills-dir']) throw new Error('--codex-home 与 --skills-dir 不能同时使用。');
  return args;
}

function samePath(a, b) {
  const canonical = p => (existsSync(p) ? realpathSync(p) : resolve(p)).toLowerCase();
  return canonical(a) === canonical(b);
}

function entryText(root, nodeBin) {
  const source = join(root, 'SKILL.md').replaceAll('\\', '/');
  return `---\nname: codex-zcode-tandem\ndescription: Coordinate Codex and native ZCode over ACP on Windows for delegated implementation, testing, review, progress, steering and recovery.\n---\n\n# Codex × ZCode · Tandem\n\n<!-- generated by codex-zcode-tandem setup -->\nRead the [complete skill instructions](<${source}>) and only the references needed for this task.\n\nSource root: ${root}\nNode: ${nodeBin}\nRunner: ${join(root, 'runtime', 'run-task.mjs')}\nControls: ${join(root, 'runtime', 'control.mjs')}\n\nThese paths belong to this installation. Do not use another person's paths or login configuration. This public skill does not replace a separate zcode-native installation.\n`;
}

export function inspectSetup(args, { root = ROOT, home = homedir(), env = process.env,
  platform = process.platform, nodeVersion = process.versions.node, nodeBin = process.execPath } = {}) {
  assertSupportedHost({ platform, nodeVersion });
  root = realpathSync(root);
  const runtime = join(root, 'runtime');
  const saved = loadConfigFile(runtime);
  const discovered = discoverPaths({ env, home, platform });
  const paths = { zcodeBin: discovered.zcodeBin, providerFile: discovered.providerFile,
    taskkillPath: discovered.taskkillPath, ...saved };
  if (args['--zcode-bin']) paths.zcodeBin = resolve(args['--zcode-bin']);
  if (args['--provider-file']) paths.providerFile = resolve(args['--provider-file']);
  const config = buildConfig(paths, {});
  for (const key of ['zcodeBin', 'providerFile', 'taskkillPath']) config[key] = resolve(runtime, config[key]);
  const failures = [];
  if (!isFile(join(root, 'SKILL.md'))) failures.push('缺少源码目录的 SKILL.md。');
  if (!isFile(config.zcodeBin)) failures.push('未找到 zcode.cjs；用 --zcode-bin 指定 ZCode 安装目录中的 resources/glm/zcode.cjs。');
  if (args['--provider-file'] && !isFile(config.providerFile)) failures.push('--provider-file 指定的自定义供应商配置不存在；它不是 Coding Plan 登录的必备文件。');
  if (!isFile(config.taskkillPath)) failures.push('未找到 Windows taskkill.exe，无法保证任务进程清理。');
  const dependency = join(runtime, 'node_modules', 'zcode-acp-server', 'package.json');
  if (!isFile(dependency)) failures.push('尚未安装依赖；在源码目录执行 npm.cmd ci --prefix runtime --ignore-scripts --no-audit --no-fund。');
  else if (JSON.parse(readFileSync(dependency, 'utf8')).version !== '0.65.1') failures.push('ACP 依赖不是锁定的 0.65.1，请重新执行 npm ci。');
  const standard = join(home, '.agents', 'skills', 'codex-zcode-tandem');
  const legacy = join(resolve(env.CODEX_HOME || join(home, '.codex')), 'skills', 'codex-zcode-tandem');
  let skillDir;
  if (args['--skills-dir']) skillDir = join(resolve(args['--skills-dir']), 'codex-zcode-tandem');
  else if (args['--codex-home']) skillDir = join(resolve(args['--codex-home']), 'skills', 'codex-zcode-tandem');
  else {
    const hasStandard = isFile(join(standard, 'SKILL.md'));
    const hasLegacy = isFile(join(legacy, 'SKILL.md'));
    if (hasStandard && hasLegacy && !samePath(standard, legacy)) failures.push('检测到标准目录和旧目录各有同名技能；请用 --skills-dir 或 --codex-home 选择入口，避免重复安装。');
    skillDir = hasLegacy && !hasStandard ? legacy : standard;
  }
  const skillFile = join(skillDir, 'SKILL.md');
  const direct = samePath(root, skillDir);
  const text = direct ? null : entryText(root, nodeBin);
  const previous = isFile(skillFile) ? readFileSync(skillFile, 'utf8') : null;
  if (!args['--check'] && !direct && previous !== null && previous !== text && !args['--replace']) {
    failures.push('发现已有同名技能；使用 --replace 明确更新，安装器会先备份原入口，保留其他文件。');
  }
  if (failures.length) throw new Error(failures.join('\n'));
  return { root, runtime, configFile: join(runtime, 'config.json'), skillDir, skillFile, direct,
    previous, text, saved, config, nodeBin, pathsVerified: true };
}

function atomicWrite(file, text) {
  const temporary = `${file}.${randomUUID()}.tmp`;
  try {
    writeFileSync(temporary, text, { encoding: 'utf8', flag: 'wx' });
    renameSync(temporary, file);
  } finally {
    if (existsSync(temporary)) unlinkSync(temporary);
  }
}

function backup(file) {
  if (!isFile(file)) return null;
  const path = `${file}.backup-${Date.now()}-${randomUUID()}`;
  writeFileSync(path, readFileSync(file), { flag: 'wx' });
  return path;
}

export function installSetup(plan, args) {
  const result = { status: args['--check'] ? 'checked' : 'installed', root: plan.root,
    skillFile: plan.skillFile, node: SUPPORTED_NODE, acp: '0.65.1',
    optionalProviderConfigPresent: isFile(plan.config.providerFile),
    note: '本地路径与依赖检查通过；自定义供应商配置可缺省。probe 验证连接与有效模型，真实推理仍需有效登录及额度。', backups: [] };
  if (args['--check']) return result;
  const configText = JSON.stringify({ ...plan.saved,
    zcodeBin: plan.config.zcodeBin, providerFile: plan.config.providerFile }, null, 2) + '\n';
  if (!isFile(plan.configFile) || readFileSync(plan.configFile, 'utf8') !== configText) {
    const saved = backup(plan.configFile);
    if (saved) result.backups.push(saved);
    atomicWrite(plan.configFile, configText);
  }
  if (!plan.direct && plan.previous !== plan.text) {
    mkdirSync(plan.skillDir, { recursive: true });
    const saved = backup(plan.skillFile);
    if (saved) result.backups.push(saved);
    atomicWrite(plan.skillFile, plan.text);
  }
  return result;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const args = parseArgs(process.argv.slice(2));
    if (args['--help']) console.log('用法：node scripts/setup.mjs [--check] [--replace] [--zcode-bin 路径] [--provider-file 路径] [--skills-dir 目录 | --codex-home 目录]\n--check 只检查，不写文件。新装默认 ~/.agents/skills；已有旧入口时复用。安装只写本地路径配置与技能入口，不复制凭据、不下载依赖。');
    else console.log(JSON.stringify(installSetup(inspectSetup(args), args), null, 2));
  } catch (error) {
    console.error(`ZCode 安装检查失败：\n${error.message}`);
    process.exitCode = 1;
  }
}
